/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChooseCorrectImageQuestion {
  'id' : string,
  'correctImageIndex' : bigint,
  'word' : string,
  'images' : Array<ExternalBlob>,
}
export type ExternalBlob = Uint8Array;
export interface FindTheItemPlacedItem {
  'x' : number,
  'y' : number,
  'height' : number,
  'itemLabel' : string,
  'image' : ExternalBlob,
  'width' : number,
}
export interface FindTheItemQuestion {
  'id' : string,
  'backgroundImage' : ExternalBlob,
  'items' : Array<FindTheItemPlacedItem>,
}
export interface Game {
  'id' : GameId,
  'primaryColor' : string,
  'icon' : string,
  'name' : string,
  'badges' : Array<string>,
  'tags' : Array<string>,
  'description' : string,
  'secondaryColor' : string,
}
export type GameId = string;
export interface MatchWordToImageQuestion {
  'id' : QuestionId,
  'correctOption' : Option,
  'image' : ExternalBlob,
  'options' : Array<Option>,
}
export type Option = string;
export interface PlayerSession {
  'gameId' : string,
  'correct' : bigint,
  'durationSeconds' : bigint,
  'timestamp' : bigint,
  'gameName' : string,
  'wrong' : bigint,
}
export type QuestionId = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createChooseCorrectImageQuestion' : ActorMethod<
    [GameId, string, Array<ExternalBlob>, bigint],
    ChooseCorrectImageQuestion
  >,
  'createFindTheItemQuestion' : ActorMethod<
    [GameId, ExternalBlob, Array<FindTheItemPlacedItem>],
    FindTheItemQuestion
  >,
  'createGame' : ActorMethod<
    [
      GameId,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      Array<string>,
    ],
    undefined
  >,
  'createQuestion' : ActorMethod<
    [GameId, ExternalBlob, Array<Option>, Option],
    QuestionId
  >,
  'getAllChooseCorrectImageQuestions' : ActorMethod<
    [GameId],
    Array<ChooseCorrectImageQuestion>
  >,
  'getAllFindTheItemQuestions' : ActorMethod<
    [GameId],
    Array<FindTheItemQuestion>
  >,
  'getAllGames' : ActorMethod<[], Array<Game>>,
  'getAllQuestions' : ActorMethod<[GameId], Array<MatchWordToImageQuestion>>,
  'getGameById' : ActorMethod<[GameId], Game>,
  'getGamesByTag' : ActorMethod<[string], Array<Game>>,
  'getMyGameSessions' : ActorMethod<[], Array<PlayerSession>>,
  'getQuestion' : ActorMethod<
    [GameId, QuestionId],
    [] | [MatchWordToImageQuestion]
  >,
  'saveGameSession' : ActorMethod<
    [string, string, bigint, bigint, bigint],
    undefined
  >,
  'updateChooseCorrectImageQuestion' : ActorMethod<
    [GameId, string, string, Array<ExternalBlob>, bigint],
    undefined
  >,
  'updateFindTheItemQuestion' : ActorMethod<
    [GameId, string, ExternalBlob, Array<FindTheItemPlacedItem>],
    undefined
  >,
  'updateGame' : ActorMethod<
    [
      GameId,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      Array<string>,
    ],
    undefined
  >,
  'updateQuestion' : ActorMethod<
    [GameId, QuestionId, ExternalBlob, Array<Option>, Option],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];