/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GameId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ChooseCorrectImageQuestion = IDL.Record({
  'id' : IDL.Text,
  'correctImageIndex' : IDL.Nat,
  'word' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const FindTheItemPlacedItem = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'height' : IDL.Float64,
  'itemLabel' : IDL.Text,
  'image' : ExternalBlob,
  'width' : IDL.Float64,
});
export const FindTheItemQuestion = IDL.Record({
  'id' : IDL.Text,
  'backgroundImage' : ExternalBlob,
  'items' : IDL.Vec(FindTheItemPlacedItem),
});
export const Option = IDL.Text;
export const QuestionId = IDL.Text;
export const Game = IDL.Record({
  'id' : GameId,
  'primaryColor' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'secondaryColor' : IDL.Text,
});
export const MatchWordToImageQuestion = IDL.Record({
  'id' : QuestionId,
  'correctOption' : Option,
  'image' : ExternalBlob,
  'options' : IDL.Vec(Option),
});
export const PlayerSession = IDL.Record({
  'gameId' : IDL.Text,
  'correct' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'timestamp' : IDL.Int,
  'gameName' : IDL.Text,
  'wrong' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createChooseCorrectImageQuestion' : IDL.Func(
      [GameId, IDL.Text, IDL.Vec(ExternalBlob), IDL.Nat],
      [ChooseCorrectImageQuestion],
      [],
    ),
  'createFindTheItemQuestion' : IDL.Func(
      [GameId, ExternalBlob, IDL.Vec(FindTheItemPlacedItem)],
      [FindTheItemQuestion],
      [],
    ),
  'createGame' : IDL.Func(
      [
        GameId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'createQuestion' : IDL.Func(
      [GameId, ExternalBlob, IDL.Vec(Option), Option],
      [QuestionId],
      [],
    ),
  'getAllChooseCorrectImageQuestions' : IDL.Func(
      [GameId],
      [IDL.Vec(ChooseCorrectImageQuestion)],
      ['query'],
    ),
  'getAllFindTheItemQuestions' : IDL.Func(
      [GameId],
      [IDL.Vec(FindTheItemQuestion)],
      ['query'],
    ),
  'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getAllQuestions' : IDL.Func(
      [GameId],
      [IDL.Vec(MatchWordToImageQuestion)],
      ['query'],
    ),
  'getGameById' : IDL.Func([GameId], [Game], ['query']),
  'getGamesByTag' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
  'getMyGameSessions' : IDL.Func([], [IDL.Vec(PlayerSession)], ['query']),
  'getQuestion' : IDL.Func(
      [GameId, QuestionId],
      [IDL.Opt(MatchWordToImageQuestion)],
      ['query'],
    ),
  'saveGameSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateChooseCorrectImageQuestion' : IDL.Func(
      [GameId, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), IDL.Nat],
      [],
      [],
    ),
  'updateFindTheItemQuestion' : IDL.Func(
      [GameId, IDL.Text, ExternalBlob, IDL.Vec(FindTheItemPlacedItem)],
      [],
      [],
    ),
  'updateGame' : IDL.Func(
      [
        GameId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateQuestion' : IDL.Func(
      [GameId, QuestionId, ExternalBlob, IDL.Vec(Option), Option],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GameId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ChooseCorrectImageQuestion = IDL.Record({
    'id' : IDL.Text,
    'correctImageIndex' : IDL.Nat,
    'word' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const FindTheItemPlacedItem = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'height' : IDL.Float64,
    'itemLabel' : IDL.Text,
    'image' : ExternalBlob,
    'width' : IDL.Float64,
  });
  const FindTheItemQuestion = IDL.Record({
    'id' : IDL.Text,
    'backgroundImage' : ExternalBlob,
    'items' : IDL.Vec(FindTheItemPlacedItem),
  });
  const Option = IDL.Text;
  const QuestionId = IDL.Text;
  const Game = IDL.Record({
    'id' : GameId,
    'primaryColor' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'secondaryColor' : IDL.Text,
  });
  const MatchWordToImageQuestion = IDL.Record({
    'id' : QuestionId,
    'correctOption' : Option,
    'image' : ExternalBlob,
    'options' : IDL.Vec(Option),
  });
  const PlayerSession = IDL.Record({
    'gameId' : IDL.Text,
    'correct' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'timestamp' : IDL.Int,
    'gameName' : IDL.Text,
    'wrong' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createChooseCorrectImageQuestion' : IDL.Func(
        [GameId, IDL.Text, IDL.Vec(ExternalBlob), IDL.Nat],
        [ChooseCorrectImageQuestion],
        [],
      ),
    'createFindTheItemQuestion' : IDL.Func(
        [GameId, ExternalBlob, IDL.Vec(FindTheItemPlacedItem)],
        [FindTheItemQuestion],
        [],
      ),
    'createGame' : IDL.Func(
        [
          GameId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'createQuestion' : IDL.Func(
        [GameId, ExternalBlob, IDL.Vec(Option), Option],
        [QuestionId],
        [],
      ),
    'getAllChooseCorrectImageQuestions' : IDL.Func(
        [GameId],
        [IDL.Vec(ChooseCorrectImageQuestion)],
        ['query'],
      ),
    'getAllFindTheItemQuestions' : IDL.Func(
        [GameId],
        [IDL.Vec(FindTheItemQuestion)],
        ['query'],
      ),
    'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getAllQuestions' : IDL.Func(
        [GameId],
        [IDL.Vec(MatchWordToImageQuestion)],
        ['query'],
      ),
    'getGameById' : IDL.Func([GameId], [Game], ['query']),
    'getGamesByTag' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
    'getMyGameSessions' : IDL.Func([], [IDL.Vec(PlayerSession)], ['query']),
    'getQuestion' : IDL.Func(
        [GameId, QuestionId],
        [IDL.Opt(MatchWordToImageQuestion)],
        ['query'],
      ),
    'saveGameSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateChooseCorrectImageQuestion' : IDL.Func(
        [GameId, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), IDL.Nat],
        [],
        [],
      ),
    'updateFindTheItemQuestion' : IDL.Func(
        [GameId, IDL.Text, ExternalBlob, IDL.Vec(FindTheItemPlacedItem)],
        [],
        [],
      ),
    'updateGame' : IDL.Func(
        [
          GameId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateQuestion' : IDL.Func(
        [GameId, QuestionId, ExternalBlob, IDL.Vec(Option), Option],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };